language: node_js
node_js:
  - "6.10.2"
install:
  - npm install
  - npm run build
deploy:
  - provider: s3
    access_key_id: "$awskey"
    secret_access_key: "$awssecret"
    bucket: "dev.tlnt.io"
    acl: public_read
    region: eu-west-1
    on:
      branch: dev
  - provider: s3
    access_key_id: "$awskey"
    secret_access_key: "$awssecret"
    bucket: "tlnt.io"
    acl: public_read
    region: eu-west-1
    on:
      tags: true
